services:
  hackaton-client:
    container_name: hackaton-client
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/usr/src/app
    stdin_open: true
    tty: true
    command: /bin/sh -c "npm i && npm run dev"
    # command: /bin/sh -c "npm i && npm run build"